### ISSUE TITLE
Inconsistent GAV

### ISSUE THREAD

**Issue by malcolmsparks** [ring-clojure/ring-spec#2]
The README says 

```clojure
[ring/ring-spec "0.0.2"]
```

Clojars says

```clojure
[ring-spec "0.0.2"]
```

Either the `project.clj` is wrong, or the README is wrong.

Would send a PR but not sure which it is

**Comment by weavejester** [comment]
Ah, thanks for pointing that out. I'll fix it.

**Comment by weavejester** [comment]
The README was correct, the project file was wrong, btw.
